import React from 'react';
import ReactAvatar from 'react-avatar';
import Slider from 'react-slick';
import './newregister.scss';
const testimonials = [
	{
		author: 'Carlos Rodriguez',
		avatar: 'https://radixhaven.com/wp-content/uploads/2020/08/Carlos.png',
		prof: 'COO',
		web: 'www.topfloormarketing.com',
		content: `"At Top Floor Marketing we’ve been using the Radix Haven Data Science and Business Intelligence Platform with great success. Due to the complex nature of our industry and the enormous amount of data generated by our clients, it was almost impossible to crunch those numbers in real time to make fast and accurate strategic decisions.
              Radix Haven, has provided a solid and user-friendly platform to help us analyze and understand our data in real time. We now have a better understanding of our client’s business cycles, our financial results and have achieved a higher ROI without the need to hire a costly full time in-house data scientist."`,
	},
	{
		author: 'Will Peralta',
		prof: 'CEO',
		avatar: 'https://radixhaven.com/wp-content/uploads/2020/08/Will.png',
		web: 'www.firstrankdigital.com',
		content: `“ We use Radix Haven as part of a reporting tool and since we’ve  been using it we’ve immediately seen a difference in our teams performance. Having our data centralized has helped our teams communication improve between departments. It especially has helped our sales team keep an eye on their performance and targets in a more visual aspect. Prior to using Radix, we had all our information on Google docs, which as you can imagine we had sheets all over the place. We now just have 5 simple tables in the tool that gives us all the information we need. I’d definitely recommend Radix Haven to any marketing agency needing to keep better control of their performance."`,
	},
];

export default function Testimonial() {
	const Testims = () =>
		testimonials.map((v, i) => {
			return (
				<div key={i} className='testimonials'>
					<div className='card-body'>
						<p>{v.content}</p>
						<div className='text-center'>
							<div>
								<span>
									<ReactAvatar src={v.avatar} className='mr-3' /> {v.author}
								</span>
							</div>
							<small>
								<b>{v.prof}</b>
							</small>
							<br />
							<small>
								<b>{v.web}</b>
							</small>
						</div>
					</div>
				</div>
			);
		});
	const settings = {
		dots: true,
		autoplay: true,
		autoplaySpeed: 10000,
		arrow: false,
	};
	return (
		<div className='container-test'>
			<Slider {...settings}>{Testims()}</Slider>
		</div>
	);
}
