import React from 'react';

import { MoneyBillAlt, UserCircle } from '@styled-icons/fa-regular';
import { Bag, Home, List } from '@styled-icons/ionicons-outline';

export const MainViewList = [
	{
		name: 'Home',
		id: 'ce2e8e1e-5f0a-425d-9119-0288e157a0c9',
		path: '/radixhaven-home',
		layout: '/admin',
		isHome: true,
		// component: Integrations,
		icon: <Home size={20} />,
		inMenu: true,
		show: true,
	},
	{
		name: 'Customers',
		id: '01881051-0510-48de-9bd9-c665e3d50f97',
		path: '/radixhaven-customers',
		layout: '/admin',
		// component: ClientsMainView,
		icon: <UserCircle size={20} />,
		inMenu: true,
		show: true,
	},
	{
		name: 'Products',
		id: '8391129d-2b0d-4edd-8203-01e580454118',
		path: '/radixhaven-products',
		layout: '/admin',
		// component: ProductsMainView,
		icon: <Bag size={20} />,

		inMenu: true,
		show: true,
	},
	{
		name: 'Subscriptions',
		id: 'f1e81113-a42e-4128-995e-f85426ce9605',
		path: '/radixhaven-subscription',
		layout: '/admin',
		// component: SubscriptionsView,
		icon: <List size={20} />,
		inMenu: true,
		show: true,
	},
	{
		id: 'c733028d-ceeb-4fa1-a29e-2a8d6f0515a7',
		name: 'Revenue',
		path: '/radixhaven-revenue',
		layout: '/admin',
		// component: SalesMainView,
		icon: <MoneyBillAlt size={20} />,
		inMenu: true,
		show: true,
	},
	{
		id: 'fc84b3da-1608-4255-8689-5e4e7a3cf90e',
		name: 'Chart Creator',
		path: '/radixhaven-chart-creator',
		layout: '/admin',
		// component: ChartCreatorView,
		icon: '',
		inMenu: false,
		show: false,
	},
	{
		id: '4df32e7b-f9a2-491b-ab67-72bb8a9415a4',
		name: 'Machine Learning',
		path: '/radixhaven-machine-learning',
		layout: '/admin',
		// component: MlMainView,
		icon: '',
		inMenu: true,
		show: true,
	},
	{
		name: 'Goals',
		id: '4f18c13a-4aeb-4590-8a13-727ba75a8421',
		path: '/radixhaven-goals',
		layout: '/admin',
		// component: GoalsView,
		icon: '',
		inMenu: true,
		show: true,
	},

	{
		name: 'Forecast',
		id: 'e2e0e82c-2074-4863-89ad-0553b8db2d99',
		path: '/radixhaven-forecast',
		layout: '/admin',
		// component: BusinessIntelligenseView,
		icon: '',
		inMenu: true,
		show: true,
	},

	{
		name: 'Account Settings',
		id: 'md_settings',
		allowed_submodules: [
			{
				id_permission: 'sm_account_form',
				name: 'My Account',
				id_parent: 'sm_account',
				icon: 'fa-user-circle-o',
				id: '1',
				description: 'Edit accounts details.',
				// component: <MyAccountPanelRefactorized />,
			},
			{
				id_permission: 'a4052e8e-4557-4022-8569-a50f1682b9eb',
				name: 'Company Details',
				id_parent: 'sm_account',
				icon: 'fa-building',
				id: '2',
				description: 'Share your company details with us so that we can customize your account',
				// component: <CompanyDetails />,
			},
			{
				id_permission: '0116eac8-20c7-4763-8970-4877a529c6c8',
				name: 'Billing & Invoicing',
				id_parent: 'sm_account',
				icon: 'fa-credit-card',
				id: '3',
				description: 'Manage your credit card information, subscription and invoices.',
				// component: <BillingInvoicing />,
			},
			{
				id_permission: '1f6f3b01-dae5-48b7-aec4-83eadac09cfe',
				name: 'Data',
				id_parent: 'sm_integration',
				icon: 'fa-database',
				id: '4',
				description: 'Connect easily your Data Source to enter the world of Radix Haven.',
				// component: <DataConnection />,
			},
			{
				id_permission: 'sm_account_form',
				name: 'Coming Soon',
				id_parent: 'sm_integration',
				icon: 'fa-cubes',
				id: '5',
				description: '',
				// component: <ComingSoon />,
			},
			{
				id_permission: '2346ef0d-6d61-4822-b4dd-92b8883afab2',
				name: 'Property',
				id_parent: 'sm_tracker',
				icon: 'fa fa-columns',
				id: '6',
				description: 'Properties store information about specific value.',
				// component: <CustomerTracker />,
			},
			{
				id_permission: '04667bfd-e722-4bad-8274-8c07206c1dd5',
				name: 'Collaborators',
				id_parent: 'sm_people',
				icon: 'fa-users',
				id: '7',
				description: 'Add or remove collaborators',
				// component: <TeamMembersModule />,
			},
		],
		path: '/radixhaven-account-settings',
		layout: '/admin',
		// component: SettingsMainView,
		inMenu: false,
		show: true,
	},
	// {
	// 	name: 'Integrations',
	//  id: null
	// 	path: '/radixhaven-add-new-integrations',
	// 	layout: '/admin',
	// component: InitialIntegrations,
	// 	inMenu: false,
	// 	show: false,
	// },
];
